name: jadehro_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.0
  flutter_easyloading: ^3.0.5
  rflutter_alert: ^2.0.7
  timer_count_down: ^2.2.2
  jwt_decoder: ^2.0.1
  carousel_slider: ^4.2.1
  persian_datetime_picker: ^2.7.0
  gap: ^3.0.1
  pinput: ^3.0.0
  flutter_spinkit: ^5.2.0
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.3
  animated_text_kit: ^4.2.2
  persian_number_utility: ^1.1.3
  flutter_spinbox: ^0.13.1
  smooth_page_indicator: ^1.1.0
  delayed_widget: ^1.1.2
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  onboarding: ^3.1.0
  url_launcher: ^6.1.11
  just_audio: ^0.9.34
  just_audio_web: ^0.4.8
  smartrefresh: ^0.0.2
  lottie: ^3.0.0
  open_street_map_search_and_pick: ^0.1.1
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner:
  build_test: ^2.2.2

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/Font/IranSans/IRANSansMobile_UltraLight.ttf
          weight: 200
        - asset: assets/Font/IranSans/IRANSansMobile_Light.ttf
          weight: 300
        - asset: assets/Font/IranSans/IRANSansMobile.ttf
          weight: 400
        - asset: assets/Font/IranSans/IRANSansMobile_Medium.ttf
          weight: 500
        - asset: assets/Font/IranSans/IRANSansMobile_Bold.ttf
          weight: 700
        - asset: assets/Font/IranSans/IRANSansMobile_Black.ttf
          weight: 900
